#!/bin/sh
export LC_ALL=C.utf8
echo "[Package Matches]" > packages.match
find .. -iname "*.c" -exec grep FR_PACKAGES '{}' ';' | sed -e 's/.*FR_PACKAGES[ ]*[(]"\([^"]*\)"[)];/\1/g' -e 's/,/\n/g' | sort -u | sed -e 's/\(.*\)/\1=/g' >> packages.match
