#!/bin/sh

if test $# -ne 1; then
	exit 1
fi

quoted=$(echo -e "$1" | awk 'BEGIN { FS = "\n" } { printf "%s\" ", $1 }' | sed -e s#\"\"##)
file_quoted="\"$quoted"
dir_quoted="\"$NAUTILUS_SCRIPT_CURRENT_URI/_$quoted"

eval "file-roller --force --extract-to=$dir_quoted $file_quoted"
